### ISSUE TITLE
GetDatasets (and in example)- confirm we are using the new (2019) WDPA Protected areas dataset

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#26]
Chrys- please confirm that we are using the updated TNC file from 2019 (that we updated here https://data.mendeley.com/datasets/2jxj4k32m2/2 in version 2), not the original earlier TNC file that was here https://data.mendeley.com/datasets/2jxj4k32m2/1 from version 1
Its not clear to me which has been uploaded to dataverse (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XIV9BL)
if any questions, please confirm with Dan.

**Comment by dcarver1** [comment]
I've checked this dataset using the getData function that is part of GapAnalysis it is pulling the TNC layer. However, it is a thinned version. only 294 of the 814 ecoregions are present. I expect this was because we were initially only going to use this for the examples. 

Extent of the current file 
![image](https://user-images.githubusercontent.com/32108872/82387187-9be80c00-99f3-11ea-843f-b98737bfed0e.png)


The codebase now relies on this layer if the user does not provide on so it needs to cover all the ecoregions of the world. 

@ccsosa please download the tnc ecoregion file from their [site](http://maps.tnc.org/gis_data.html) and update the feature on the dataverse.

**Comment by ccsosa** [comment]
Hi Dan, the file in the example was cropped to that area for convenience (package size). The complete file is in dataverse. You can get the file in dataverse using getDatasets()

**Comment by ccsosa** [comment]
> Chrys- please confirm that we are using the updated TNC file from 2019 (that we updated here https://data.mendeley.com/datasets/2jxj4k32m2/2 in version 2), not the original earlier TNC file that was here https://data.mendeley.com/datasets/2jxj4k32m2/1 from version 1
> Its not clear to me which has been uploaded to dataverse (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XIV9BL)
> if any questions, please confirm with Dan.
Colin and Dan, I confirmed this is the version of 2019. The file size in dataverse and mendeley v2 match, same as number of cells different of NA
