### ISSUE TITLE
Following discussion on the paper, make sure that Gbuffer and OccurrenceCounts aren't exported functions

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#42]

**Comment by ccsosa** [comment]
@jramirezv We are using #' @keywords internal in the documentation. Thus, those functions are not creating Rd files and they are not used in the pdf manual created. However, they are in namespace because they are used in the R package.

![image](https://user-images.githubusercontent.com/10407841/82834141-d9cab180-9e85-11ea-95b8-c0df3ab34781.png)

**Comment by jramirezv** [comment]
Ok, cool i’m closing the issue then.
