### ISSUE TITLE
Make gap map for SRSin? 

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#44]
The gap maps we are making are awesome. Really helpful. I wonder if we should take the final step and make a gap map for SRSin too? It would be a map of points (within SDM) that are outside of protected areas

**Comment by jramirezv** [comment]
Ok for me. Good idea.

**Comment by dcarver1** [comment]
This should be quick, I'll try to get something to you soon

**Comment by dcarver1** [comment]
Allright, well I've got a map, but there is  some complications. 

![image](https://user-images.githubusercontent.com/32108872/83083264-eba58380-a042-11ea-840d-079b2127957a.png)

For all other gap maps, we simply generate a raster object. 

Because SRSin requires points and a raster object, they have to be combined. 
I did this using tmap, a library we will need for visualizing summary htmls. 

The object is a tmap object, not a raster. I can export it as a tiff, but I can not convert from a tmap object to a raster object in TIFF in memory 

We can either, 
1. deliver a tmap object (not consistent with all other gap_map functions) 
2. write out the object as a tiff and read it back it as a raster and delete the written object? This seems clunkly... Not sure how it would all come together actually 

I prefer 1. 
Other's thoughts are welcomed.

**Comment by ccsosa** [comment]
What about for those pixels where occurrences are available, put a different value to keep the raster outputs philosophy?

**Comment by jramirezv** [comment]
I like Chrys’ idea. The sdm could be transformed to value NA= no species predicted presence, 0 = species present but no occurrences, 1= species present and 1 occurrence, 2= species present and 2 occurrences, and so on. This is in case more than 1 occurrence is found in single pixel.

**Comment by dcarver1** [comment]
Alright, that sounds good. I'll work on implimenting it
